stages:
  preparar_datos:
    cmd: python src/data_prep.py --params limpieza_param --outs 
      data/processed/clean.csv
    deps:
    - data/raw/sample.csv
    - data/validation_passed.txt
    - src/data_prep.py
    outs:
    - data/processed/clean.csv
  entrenar_modelo:
    cmd: python src/train.py
    deps:
    - data/processed/clean.csv
    - src/train.py
    outs:
    - models/model.pkl
    - models/model_metadata.json
  validar_datos:
    cmd: python tests/test_data_quality.py
    deps:
    - data/raw/sample.csv
    - tests/test_data_quality.py
    outs:
    - data/validation_passed.txt
  evaluar_modelo:
    cmd: python src/evaluate.py
    deps:
    - data/raw/test.csv
    - models/model.pkl
    - src/evaluate.py
    metrics:
    - metrics/evaluation.json:
        cache: false
